
service: hylet

# custom:
#   secrets: ${file(secrets.json)}
#app: your-app-name
#org: your-org-name


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

# plugins:
#   - serverless-offline
