const express = require('express')
const router = express.Router()
const test = require('./test/test.controller')
const auth = require('./auth/auth.controller')
const user = require('./user/user.controller')
const promo = require('./promo/promo.controller')
const Auth = require('./auth/auth.function')
const brand = require('./brand/brand.controller')
const page = require('./page/page.controller')
const onboard = require('./onboard/onboard.controller')
router.use('/test',test)
router.use('/',auth)
router.use('/user',Auth.isLoggedIn,user)
router.use('/promo',promo)
router.use('/b',Auth.isLoggedIn,brand)
router.use('/p',Auth.isLoggedIn,page)
router.use('/onboard',Auth.isLoggedIn,onboard)
// Add more routes here
module.exports = router